echo 'alice'->s:hello()
echo 'alice'->s:hello('bob')
echo [1,2,3]->map({i,n -> n * 2})
echo 'john'->{s -> 'hello ' .. s }()
echo 'john'->{s,b -> 'hello ' .. s .. ' ... and goodbye ' .. b .. '!' }('bob')
