#!/usr/bin/env python3
# usage: python3 vimlparser.py foo.vim

import sys
import re

def main():
    r = StringReader(viml_readfile(sys.argv[1]))
    p = VimLParser()
    c = Compiler()
    for line in c.compile(p.parse(r)):
        print(line)

class AttributeDict(dict):
    __getattribute__ = dict.__getitem__
    __setattr__ = dict.__setitem__
    __delattr__ = dict.__delitem__

pat_vim2py = {
  ":\\|\\s" : ":|\\s",
  "[-+]" : "[-+]",
  "[/?]" : "[/?]",
  "[0-9A-Za-z_]" : "[0-9A-Za-z_]",
  "[0-9a-zA-Z]" : "[0-9a-zA-Z]",
  "[@*!=><&~#]" : "[@*!=><&~#]",
  "[gj]" : "[gj]",
  "\\.\\d" : "\\.\\d",
  "\\<ARGOPT\\>" : "\\bARGOPT\\b",
  "\\<BANG\\>" : "\\bBANG\\b",
  "\\<EDITCMD\\>" : "\\bEDITCMD\\b",
  "\\<NOTRLCOM\\>" : "\\bNOTRLCOM\\b",
  "\\<TRLBAR\\>" : "\\bTRLBAR\\b",
  "\\<USECTRLV\\>" : "\\bUSECTRLV\\b",
  "\\<\\(XFILE\\|FILES\\|FILE1\\)\\>" : "\\b(XFILE|FILES|FILE1)\\b",
  "\\S" : "\\S",
  "\\a" : "[A-Za-z]",
  "\\d" : "\\d",
  "\\h" : "[A-Za-z_]",
  "\\s" : "\\s",
  "\\v^%(IDENTIFIER|INDEX|DOT|OPTION|ENV|REG)$" : "^(IDENTIFIER|INDEX|DOT|OPTION|ENV|REG)$",
  "\\v^%(IF|ELSEIF|ELSE)$" : "^(IF|ELSEIF|ELSE)$",
  "\\v^%(TRY|CATCH|FINALLY)$" : "^(TRY|CATCH|FINALLY)$",
  "\\v^%(substitute|smagic|snomagic)$" : "^(substitute|smagic|snomagic)$",
  "\\v^%(write|update)$" : "^(write|update)$",
  "\\v^d%[elete][lp]$" : "^d(elete|elet|ele|el|e)[lp]$",
  "\\v^s%(c[^sr][^i][^p]|g|i[^mlg]|I|r[^e])" : "^s(c[^sr][^i][^p]|g|i[^mlg]|I|r[^e])",
  "\\w" : "[0-9A-Za-z_]",
  "\\w\\|[:#]" : "[0-9A-Za-z_]|[:#]",
  "\\x" : "[0-9A-Fa-f]",
  "^!" : "^!",
  "^!$" : "^!$",
  "^!=" : "^!=",
  "^!=#" : "^!=#",
  "^!=?" : "^!=\\?",
  "^!\\~" : "^!~",
  "^!\\~#" : "^!~#",
  "^!\\~?" : "^!~\\?",
  "^#$" : "^#$",
  "^%" : "^%",
  "^&$" : "^&$",
  "^&&" : "^&&",
  "^&\\(g:\\|l:\\|\\w\\w\\)" : "^&(g:|l:|[0-9A-Za-z_][0-9A-Za-z_])",
  "^'" : "^'",
  "^(" : "^\(",
  "^)" : "^\)",
  "^)\\+$" : "^\)+$",
  "^+" : "^\+",
  "^++" : "^\+\+",
  "^++bad=\\(keep\\|drop\\|.\\)\\>" : "^\\+\\+bad=(keep|drop|.)\\b",
  "^++bad=drop" : "^\\+\\+bad=drop",
  "^++bad=keep" : "^\\+\\+bad=keep",
  "^++bin\\>" : "^\\+\\+bin\\b",
  "^++edit\\>" : "^\\+\\+edit\\b",
  "^++enc=\\S" : "^\\+\\+enc=\\S",
  "^++encoding=\\S" : "^\\+\\+encoding=\\S",
  "^++ff=\\(dos\\|unix\\|mac\\)\\>" : "^\\+\\+ff=(dos|unix|mac)\\b",
  "^++fileformat=\\(dos\\|unix\\|mac\\)\\>" : "^\\+\\+fileformat=(dos|unix|mac)\\b",
  "^++nobin\\>" : "^\\+\\+nobin\\b",
  "^," : "^,",
  "^-" : "^-",
  "^/" : "^/",
  "^0x\\x" : "^0x[0-9A-Fa-f]",
  "^:" : "^:",
  "^;" : "^;",
  "^<" : "^<",
  "^<#" : "^<#",
  "^<$" : "^<$",
  "^<=" : "^<=",
  "^<=#" : "^<=#",
  "^<=?" : "^<=\\?",
  "^<?" : "^<\\?",
  "^<[Ss][Ii][Dd]>\\h" : "^<[Ss][Ii][Dd]>[A-Za-z_]",
  "^=" : "^=",
  "^=$" : "^=$",
  "^==" : "^==",
  "^==#" : "^==#",
  "^==?" : "^==\\?",
  "^=\\~" : "^=~",
  "^=\\~#" : "^=~#",
  "^=\\~?" : "^=~\\?",
  "^>" : "^>",
  "^>#" : "^>#",
  "^>$" : "^>$",
  "^>=" : "^>=",
  "^>=#" : "^>=#",
  "^>=?" : "^>=\\?",
  "^>?" : "^>\\?",
  "^?" : "^\\?",
  "^@$" : "^@$",
  "^@." : "^@.",
  "^FUNCTION$" : "^FUNCTION$",
  "^N\\%[ext]$" : "^N(ext|ex|e)$",
  "^P\\%[rint]$" : "^P(rint|rin|ri|r)$",
  "^X$" : "^X$",
  "^[<>]$" : "^[<>]$",
  "^[A-Z]" : "^[A-Z]",
  "^\"" : "^\"",
  "^\\$\\w\\+" : "^\\$[0-9A-Za-z_]+",
  "^\\(!\\|global\\|vglobal\\)$" : "^(!|global|vglobal)$",
  "^\\(WHILE\\|FOR\\)$" : "^(WHILE|FOR)$",
  "^\\(vimgrep\\|vimgrepadd\\|lvimgrep\\|lvimgrepadd\\)$" : "^(vimgrep|vimgrepadd|lvimgrep|lvimgrepadd)$",
  "^\\*" : "^\\*",
  "^\\*$" : "^\\*$",
  "^\\." : "^\\.",
  "^\\[" : "^\[",
  "^\\d" : "^\\d",
  "^\\h" : "^[A-Za-z_]",
  "^\\s" : "^\\s",
  "^\\~$" : "^~$",
  "^]" : "^]",
  "^`" : "^`",
  "^a\\%[ppend]$" : "^a(ppend|ppen|ppe|pp|p)?$",
  "^ab\\%[breviate]$" : "^ab(breviate|breviat|brevia|brevi|brev|bre|br|b)?$",
  "^abc\\%[lear]$" : "^abc(lear|lea|le|l)?$",
  "^abo\\%[veleft]$" : "^abo(veleft|velef|vele|vel|ve|v)?$",
  "^al\\%[l]$" : "^al(l)?$",
  "^am\\%[enu]$" : "^am(enu|en|e)?$",
  "^an\\%[oremenu]$" : "^an(oremenu|oremen|oreme|orem|ore|or|o)?$",
  "^ar\\%[gs]$" : "^ar(gs|g)?$",
  "^arga\\%[dd]$" : "^arga(dd|d)?$",
  "^argd\\%[elete]$" : "^argd(elete|elet|ele|el|e)?$",
  "^argdo$" : "^argdo$",
  "^arge\\%[dit]$" : "^arge(dit|di|d)?$",
  "^argg\\%[lobal]$" : "^argg(lobal|loba|lob|lo|l)?$",
  "^argl\\%[ocal]$" : "^argl(ocal|oca|oc|o)?$",
  "^argu\\%[ment]$" : "^argu(ment|men|me|m)?$",
  "^as\\%[cii]$" : "^as(cii|ci|c)?$",
  "^au\\%[tocmd]$" : "^au(tocmd|tocm|toc|to|t)?$",
  "^aug\\%[roup]$" : "^aug(roup|rou|ro|r)?$",
  "^aun\\%[menu]$" : "^aun(menu|men|me|m)?$",
  "^bN\\%[ext]$" : "^bN(ext|ex|e)?$",
  "^b\\%[uffer]$" : "^b(uffer|uffe|uff|uf|u)?$",
  "^ba\\%[ll]$" : "^ba(ll|l)?$",
  "^bad\\%[d]$" : "^bad(d)?$",
  "^bd\\%[elete]$" : "^bd(elete|elet|ele|el|e)?$",
  "^be\\%[have]$" : "^be(have|hav|ha|h)?$",
  "^bel\\%[owright]$" : "^bel(owright|owrigh|owrig|owri|owr|ow|o)?$",
  "^bf\\%[irst]$" : "^bf(irst|irs|ir|i)?$",
  "^bl\\%[ast]$" : "^bl(ast|as|a)?$",
  "^bm\\%[odified]$" : "^bm(odified|odifie|odifi|odif|odi|od|o)?$",
  "^bn\\%[ext]$" : "^bn(ext|ex|e)?$",
  "^bo\\%[tright]$" : "^bo(tright|trigh|trig|tri|tr|t)?$",
  "^bp\\%[revious]$" : "^bp(revious|reviou|revio|revi|rev|re|r)?$",
  "^br\\%[ewind]$" : "^br(ewind|ewin|ewi|ew|e)?$",
  "^brea\\%[k]$" : "^brea(k)?$",
  "^breaka\\%[dd]$" : "^breaka(dd|d)?$",
  "^breakd\\%[el]$" : "^breakd(el|e)?$",
  "^breakl\\%[ist]$" : "^breakl(ist|is|i)?$",
  "^bro\\%[wse]$" : "^bro(wse|ws|w)?$",
  "^bufdo$" : "^bufdo$",
  "^buffers$" : "^buffers$",
  "^bun\\%[load]$" : "^bun(load|loa|lo|l)?$",
  "^bw\\%[ipeout]$" : "^bw(ipeout|ipeou|ipeo|ipe|ip|i)?$",
  "^cN\\%[ext]$" : "^cN(ext|ex|e)?$",
  "^cNf\\%[ile]$" : "^cNf(ile|il|i)?$",
  "^c\\%[hange]$" : "^c(hange|hang|han|ha|h)?$",
  "^ca\\%[bbrev]$" : "^ca(bbrev|bbre|bbr|bb|b)?$",
  "^cabc\\%[lear]$" : "^cabc(lear|lea|le|l)?$",
  "^cad\\%[dexpr]$" : "^cad(dexpr|dexp|dex|de|d)?$",
  "^caddb\\%[uffer]$" : "^caddb(uffer|uffe|uff|uf|u)?$",
  "^caddf\\%[ile]$" : "^caddf(ile|il|i)?$",
  "^cal\\%[l]$" : "^cal(l)?$",
  "^cat\\%[ch]$" : "^cat(ch|c)?$",
  "^cb\\%[uffer]$" : "^cb(uffer|uffe|uff|uf|u)?$",
  "^cc$" : "^cc$",
  "^ccl\\%[ose]$" : "^ccl(ose|os|o)?$",
  "^cd$" : "^cd$",
  "^ce\\%[nter]$" : "^ce(nter|nte|nt|n)?$",
  "^cex\\%[pr]$" : "^cex(pr|p)?$",
  "^cf\\%[ile]$" : "^cf(ile|il|i)?$",
  "^cfir\\%[st]$" : "^cfir(st|s)?$",
  "^cg\\%[etfile]$" : "^cg(etfile|etfil|etfi|etf|et|e)?$",
  "^cgetb\\%[uffer]$" : "^cgetb(uffer|uffe|uff|uf|u)?$",
  "^cgete\\%[xpr]$" : "^cgete(xpr|xp|x)?$",
  "^changes$" : "^changes$",
  "^chd\\%[ir]$" : "^chd(ir|i)?$",
  "^che\\%[ckpath]$" : "^che(ckpath|ckpat|ckpa|ckp|ck|c)?$",
  "^checkt\\%[ime]$" : "^checkt(ime|im|i)?$",
  "^cl\\%[ist]$" : "^cl(ist|is|i)?$",
  "^cla\\%[st]$" : "^cla(st|s)?$",
  "^clo\\%[se]$" : "^clo(se|s)?$",
  "^cm\\%[ap]$" : "^cm(ap|a)?$",
  "^cmapc\\%[lear]$" : "^cmapc(lear|lea|le|l)?$",
  "^cme\\%[nu]$" : "^cme(nu|n)?$",
  "^cn\\%[ext]$" : "^cn(ext|ex|e)?$",
  "^cnew\\%[er]$" : "^cnew(er|e)?$",
  "^cnf\\%[ile]$" : "^cnf(ile|il|i)?$",
  "^cno\\%[remap]$" : "^cno(remap|rema|rem|re|r)?$",
  "^cnorea\\%[bbrev]$" : "^cnorea(bbrev|bbre|bbr|bb|b)?$",
  "^cnoreme\\%[nu]$" : "^cnoreme(nu|n)?$",
  "^co\\%[py]$" : "^co(py|p)?$",
  "^col\\%[der]$" : "^col(der|de|d)?$",
  "^colo\\%[rscheme]$" : "^colo(rscheme|rschem|rsche|rsch|rsc|rs|r)?$",
  "^com\\%[mand]$" : "^com(mand|man|ma|m)?$",
  "^comc\\%[lear]$" : "^comc(lear|lea|le|l)?$",
  "^comp\\%[iler]$" : "^comp(iler|ile|il|i)?$",
  "^con\\%[tinue]$" : "^con(tinue|tinu|tin|ti|t)?$",
  "^conf\\%[irm]$" : "^conf(irm|ir|i)?$",
  "^cope\\%[n]$" : "^cope(n)?$",
  "^cp\\%[revious]$" : "^cp(revious|reviou|revio|revi|rev|re|r)?$",
  "^cpf\\%[ile]$" : "^cpf(ile|il|i)?$",
  "^cq\\%[uit]$" : "^cq(uit|ui|u)?$",
  "^cr\\%[ewind]$" : "^cr(ewind|ewin|ewi|ew|e)?$",
  "^cs\\%[cope]$" : "^cs(cope|cop|co|c)?$",
  "^cst\\%[ag]$" : "^cst(ag|a)?$",
  "^cu\\%[nmap]$" : "^cu(nmap|nma|nm|n)?$",
  "^cuna\\%[bbrev]$" : "^cuna(bbrev|bbre|bbr|bb|b)?$",
  "^cunme\\%[nu]$" : "^cunme(nu|n)?$",
  "^cw\\%[indow]$" : "^cw(indow|indo|ind|in|i)?$",
  "^d\\%[elete]$" : "^d(elete|elet|ele|el|e)?$",
  "^deb\\%[ug]$" : "^deb(ug|u)?$",
  "^debugg\\%[reedy]$" : "^debugg(reedy|reed|ree|re|r)?$",
  "^delc\\%[ommand]$" : "^delc(ommand|omman|omma|omm|om|o)?$",
  "^delf\\%[unction]$" : "^delf(unction|unctio|uncti|unct|unc|un|u)?$",
  "^delm\\%[arks]$" : "^delm(arks|ark|ar|a)?$",
  "^di\\%[splay]$" : "^di(splay|spla|spl|sp|s)?$",
  "^dif\\%[fupdate]$" : "^dif(fupdate|fupdat|fupda|fupd|fup|fu|f)?$",
  "^diffg\\%[et]$" : "^diffg(et|e)?$",
  "^diffo\\%[ff]$" : "^diffo(ff|f)?$",
  "^diffp\\%[atch]$" : "^diffp(atch|atc|at|a)?$",
  "^diffpu\\%[t]$" : "^diffpu(t)?$",
  "^diffs\\%[plit]$" : "^diffs(plit|pli|pl|p)?$",
  "^diffthis$" : "^diffthis$",
  "^dig\\%[raphs]$" : "^dig(raphs|raph|rap|ra|r)?$",
  "^dj\\%[ump]$" : "^dj(ump|um|u)?$",
  "^dl\\%[ist]$" : "^dl(ist|is|i)?$",
  "^do\\%[autocmd]$" : "^do(autocmd|autocm|autoc|auto|aut|au|a)?$",
  "^doautoa\\%[ll]$" : "^doautoa(ll|l)?$",
  "^dr\\%[op]$" : "^dr(op|o)?$",
  "^ds\\%[earch]$" : "^ds(earch|earc|ear|ea|e)?$",
  "^dsp\\%[lit]$" : "^dsp(lit|li|l)?$",
  "^e\\%[dit]$" : "^e(dit|di|d)?$",
  "^ea\\%[rlier]$" : "^ea(rlier|rlie|rli|rl|r)?$",
  "^ec\\%[ho]$" : "^ec(ho|h)?$",
  "^echoe\\%[rr]$" : "^echoe(rr|r)?$",
  "^echoh\\%[l]$" : "^echoh(l)?$",
  "^echom\\%[sg]$" : "^echom(sg|s)?$",
  "^echon$" : "^echon$",
  "^el\\%[se]$" : "^el(se|s)?$",
  "^elsei\\%[f]$" : "^elsei(f)?$",
  "^em\\%[enu]$" : "^em(enu|en|e)?$",
  "^en\\%[dif]$" : "^en(dif|di|d)?$",
  "^endf\\%[unction]$" : "^endf(unction|unctio|uncti|unct|unc|un|u)?$",
  "^endfo\\%[r]$" : "^endfo(r)?$",
  "^endt\\%[ry]$" : "^endt(ry|r)?$",
  "^endw\\%[hile]$" : "^endw(hile|hil|hi|h)?$",
  "^ene\\%[w]$" : "^ene(w)?$",
  "^ex$" : "^ex$",
  "^exe\\%[cute]$" : "^exe(cute|cut|cu|c)?$",
  "^exi\\%[t]$" : "^exi(t)?$",
  "^exu\\%[sage]$" : "^exu(sage|sag|sa|s)?$",
  "^f\\%[ile]$" : "^f(ile|il|i)?$",
  "^files$" : "^files$",
  "^filet\\%[ype]$" : "^filet(ype|yp|y)?$",
  "^fin\\%[d]$" : "^fin(d)?$",
  "^fina\\%[lly]$" : "^fina(lly|ll|l)?$",
  "^fini\\%[sh]$" : "^fini(sh|s)?$",
  "^fir\\%[st]$" : "^fir(st|s)?$",
  "^fix\\%[del]$" : "^fix(del|de|d)?$",
  "^fo\\%[ld]$" : "^fo(ld|l)?$",
  "^foldc\\%[lose]$" : "^foldc(lose|los|lo|l)?$",
  "^foldd\\%[oopen]$" : "^foldd(oopen|oope|oop|oo|o)?$",
  "^folddoc\\%[losed]$" : "^folddoc(losed|lose|los|lo|l)?$",
  "^foldo\\%[pen]$" : "^foldo(pen|pe|p)?$",
  "^for$" : "^for$",
  "^fu\\%[nction]$" : "^fu(nction|nctio|ncti|nct|nc|n)?$",
  "^g\\%[lobal]$" : "^g(lobal|loba|lob|lo|l)?$",
  "^go\\%[to]$" : "^go(to|t)?$",
  "^gr\\%[ep]$" : "^gr(ep|e)?$",
  "^grepa\\%[dd]$" : "^grepa(dd|d)?$",
  "^gu\\%[i]$" : "^gu(i)?$",
  "^gv\\%[im]$" : "^gv(im|i)?$",
  "^h\\%[elp]$" : "^h(elp|el|e)?$",
  "^ha\\%[rdcopy]$" : "^ha(rdcopy|rdcop|rdco|rdc|rd|r)?$",
  "^helpf\\%[ind]$" : "^helpf(ind|in|i)?$",
  "^helpg\\%[rep]$" : "^helpg(rep|re|r)?$",
  "^helpt\\%[ags]$" : "^helpt(ags|ag|a)?$",
  "^hi\\%[ghlight]$" : "^hi(ghlight|ghligh|ghlig|ghli|ghl|gh|g)?$",
  "^hid\\%[e]$" : "^hid(e)?$",
  "^his\\%[tory]$" : "^his(tory|tor|to|t)?$",
  "^i\\%[nsert]$" : "^i(nsert|nser|nse|ns|n)?$",
  "^ia\\%[bbrev]$" : "^ia(bbrev|bbre|bbr|bb|b)?$",
  "^iabc\\%[lear]$" : "^iabc(lear|lea|le|l)?$",
  "^if$" : "^if$",
  "^ij\\%[ump]$" : "^ij(ump|um|u)?$",
  "^il\\%[ist]$" : "^il(ist|is|i)?$",
  "^im\\%[ap]$" : "^im(ap|a)?$",
  "^imapc\\%[lear]$" : "^imapc(lear|lea|le|l)?$",
  "^ime\\%[nu]$" : "^ime(nu|n)?$",
  "^ino\\%[remap]$" : "^ino(remap|rema|rem|re|r)?$",
  "^inorea\\%[bbrev]$" : "^inorea(bbrev|bbre|bbr|bb|b)?$",
  "^inoreme\\%[nu]$" : "^inoreme(nu|n)?$",
  "^int\\%[ro]$" : "^int(ro|r)?$",
  "^is#" : "^is#",
  "^is?" : "^is\\?",
  "^is\\%[earch]$" : "^is(earch|earc|ear|ea|e)?$",
  "^is\\>" : "^is\\b",
  "^isnot#" : "^isnot#",
  "^isnot?" : "^isnot\\?",
  "^isnot\\>" : "^isnot\\b",
  "^isp\\%[lit]$" : "^isp(lit|li|l)?$",
  "^iu\\%[nmap]$" : "^iu(nmap|nma|nm|n)?$",
  "^iuna\\%[bbrev]$" : "^iuna(bbrev|bbre|bbr|bb|b)?$",
  "^iunme\\%[nu]$" : "^iunme(nu|n)?$",
  "^j\\%[oin]$" : "^j(oin|oi|o)?$",
  "^ju\\%[mps]$" : "^ju(mps|mp|m)?$",
  "^k$" : "^k$",
  "^kee\\%[pmarks]$" : "^kee(pmarks|pmark|pmar|pma|pm|p)?$",
  "^keepa\\%[lt]$" : "^keepa(lt|l)?$",
  "^keepj\\%[umps]$" : "^keepj(umps|ump|um|u)?$",
  "^lN\\%[ext]$" : "^lN(ext|ex|e)?$",
  "^lNf\\%[ile]$" : "^lNf(ile|il|i)?$",
  "^l\\%[ist]$" : "^l(ist|is|i)?$",
  "^la\\%[st]$" : "^la(st|s)?$",
  "^lad\\%[dexpr]$" : "^lad(dexpr|dexp|dex|de|d)?$",
  "^laddb\\%[uffer]$" : "^laddb(uffer|uffe|uff|uf|u)?$",
  "^laddf\\%[ile]$" : "^laddf(ile|il|i)?$",
  "^lan\\%[guage]$" : "^lan(guage|guag|gua|gu|g)?$",
  "^lat\\%[er]$" : "^lat(er|e)?$",
  "^lb\\%[uffer]$" : "^lb(uffer|uffe|uff|uf|u)?$",
  "^lc\\%[d]$" : "^lc(d)?$",
  "^lch\\%[dir]$" : "^lch(dir|di|d)?$",
  "^lcl\\%[ose]$" : "^lcl(ose|os|o)?$",
  "^lcs\\%[cope]$" : "^lcs(cope|cop|co|c)?$",
  "^le\\%[ft]$" : "^le(ft|f)?$",
  "^lefta\\%[bove]$" : "^lefta(bove|bov|bo|b)?$",
  "^let$" : "^let$",
  "^lex\\%[pr]$" : "^lex(pr|p)?$",
  "^lf\\%[ile]$" : "^lf(ile|il|i)?$",
  "^lfir\\%[st]$" : "^lfir(st|s)?$",
  "^lg\\%[etfile]$" : "^lg(etfile|etfil|etfi|etf|et|e)?$",
  "^lgetb\\%[uffer]$" : "^lgetb(uffer|uffe|uff|uf|u)?$",
  "^lgete\\%[xpr]$" : "^lgete(xpr|xp|x)?$",
  "^lgr\\%[ep]$" : "^lgr(ep|e)?$",
  "^lgrepa\\%[dd]$" : "^lgrepa(dd|d)?$",
  "^lh\\%[elpgrep]$" : "^lh(elpgrep|elpgre|elpgr|elpg|elp|el|e)?$",
  "^ll$" : "^ll$",
  "^lla\\%[st]$" : "^lla(st|s)?$",
  "^lli\\%[st]$" : "^lli(st|s)?$",
  "^lm\\%[ap]$" : "^lm(ap|a)?$",
  "^lmak\\%[e]$" : "^lmak(e)?$",
  "^lmapc\\%[lear]$" : "^lmapc(lear|lea|le|l)?$",
  "^ln\\%[oremap]$" : "^ln(oremap|orema|orem|ore|or|o)?$",
  "^lne\\%[xt]$" : "^lne(xt|x)?$",
  "^lnew\\%[er]$" : "^lnew(er|e)?$",
  "^lnf\\%[ile]$" : "^lnf(ile|il|i)?$",
  "^lo\\%[adview]$" : "^lo(adview|advie|advi|adv|ad|a)?$",
  "^loadk\\%[eymap]$" : "^loadk(eymap|eyma|eym|ey|e)?$",
  "^loc\\%[kmarks]$" : "^loc(kmarks|kmark|kmar|kma|km|k)?$",
  "^lockv\\%[ar]$" : "^lockv(ar|a)?$",
  "^lol\\%[der]$" : "^lol(der|de|d)?$",
  "^lope\\%[n]$" : "^lope(n)?$",
  "^lp\\%[revious]$" : "^lp(revious|reviou|revio|revi|rev|re|r)?$",
  "^lpf\\%[ile]$" : "^lpf(ile|il|i)?$",
  "^lr\\%[ewind]$" : "^lr(ewind|ewin|ewi|ew|e)?$",
  "^ls$" : "^ls$",
  "^lt\\%[ag]$" : "^lt(ag|a)?$",
  "^lu\\%[nmap]$" : "^lu(nmap|nma|nm|n)?$",
  "^lua$" : "^lua$",
  "^luad\\%[o]$" : "^luad(o)?$",
  "^luaf\\%[ile]$" : "^luaf(ile|il|i)?$",
  "^lv\\%[imgrep]$" : "^lv(imgrep|imgre|imgr|img|im|i)?$",
  "^lvimgrepa\\%[dd]$" : "^lvimgrepa(dd|d)?$",
  "^lw\\%[indow]$" : "^lw(indow|indo|ind|in|i)?$",
  "^m\\%[ove]$" : "^m(ove|ov|o)?$",
  "^ma\\%[rk]$" : "^ma(rk|r)?$",
  "^mak\\%[e]$" : "^mak(e)?$",
  "^map$" : "^map$",
  "^mapc\\%[lear]$" : "^mapc(lear|lea|le|l)?$",
  "^marks$" : "^marks$",
  "^mat\\%[ch]$" : "^mat(ch|c)?$",
  "^me\\%[nu]$" : "^me(nu|n)?$",
  "^menut\\%[ranslate]$" : "^menut(ranslate|ranslat|ransla|ransl|rans|ran|ra|r)?$",
  "^mes\\%[sages]$" : "^mes(sages|sage|sag|sa|s)?$",
  "^mk\\%[exrc]$" : "^mk(exrc|exr|ex|e)?$",
  "^mks\\%[ession]$" : "^mks(ession|essio|essi|ess|es|e)?$",
  "^mksp\\%[ell]$" : "^mksp(ell|el|e)?$",
  "^mkv\\%[imrc]$" : "^mkv(imrc|imr|im|i)?$",
  "^mkvie\\%[w]$" : "^mkvie(w)?$",
  "^mod\\%[e]$" : "^mod(e)?$",
  "^mz\\%[scheme]$" : "^mz(scheme|schem|sche|sch|sc|s)?$",
  "^mzf\\%[ile]$" : "^mzf(ile|il|i)?$",
  "^n\\%[ext]$" : "^n(ext|ex|e)?$",
  "^nb\\%[key]$" : "^nb(key|ke|k)?$",
  "^nbc\\%[lose]$" : "^nbc(lose|los|lo|l)?$",
  "^nbs\\%[art]$" : "^nbs(art|ar|a)?$",
  "^new$" : "^new$",
  "^nm\\%[ap]$" : "^nm(ap|a)?$",
  "^nmapc\\%[lear]$" : "^nmapc(lear|lea|le|l)?$",
  "^nme\\%[nu]$" : "^nme(nu|n)?$",
  "^nn\\%[oremap]$" : "^nn(oremap|orema|orem|ore|or|o)?$",
  "^nnoreme\\%[nu]$" : "^nnoreme(nu|n)?$",
  "^no\\%[remap]$" : "^no(remap|rema|rem|re|r)?$",
  "^noa\\%[utocmd]$" : "^noa(utocmd|utocm|utoc|uto|ut|u)?$",
  "^noh\\%[lsearch]$" : "^noh(lsearch|lsearc|lsear|lsea|lse|ls|l)?$",
  "^norea\\%[bbrev]$" : "^norea(bbrev|bbre|bbr|bb|b)?$",
  "^noreme\\%[nu]$" : "^noreme(nu|n)?$",
  "^norm\\%[al]$" : "^norm(al|a)?$",
  "^nu\\%[mber]$" : "^nu(mber|mbe|mb|m)?$",
  "^nun\\%[map]$" : "^nun(map|ma|m)?$",
  "^nunme\\%[nu]$" : "^nunme(nu|n)?$",
  "^o\\%[pen]$" : "^o(pen|pe|p)?$",
  "^ol\\%[dfiles]$" : "^ol(dfiles|dfile|dfil|dfi|df|d)?$",
  "^om\\%[ap]$" : "^om(ap|a)?$",
  "^omapc\\%[lear]$" : "^omapc(lear|lea|le|l)?$",
  "^ome\\%[nu]$" : "^ome(nu|n)?$",
  "^on\\%[ly]$" : "^on(ly|l)?$",
  "^ono\\%[remap]$" : "^ono(remap|rema|rem|re|r)?$",
  "^onoreme\\%[nu]$" : "^onoreme(nu|n)?$",
  "^opt\\%[ions]$" : "^opt(ions|ion|io|i)?$",
  "^ou\\%[nmap]$" : "^ou(nmap|nma|nm|n)?$",
  "^ounme\\%[nu]$" : "^ounme(nu|n)?$",
  "^ow\\%[nsyntax]$" : "^ow(nsyntax|nsynta|nsynt|nsyn|nsy|ns|n)?$",
  "^p\\%[rint]$" : "^p(rint|rin|ri|r)?$",
  "^pc\\%[lose]$" : "^pc(lose|los|lo|l)?$",
  "^pe\\%[rl]$" : "^pe(rl|r)?$",
  "^ped\\%[it]$" : "^ped(it|i)?$",
  "^perld\\%[o]$" : "^perld(o)?$",
  "^po\\%[p]$" : "^po(p)?$",
  "^popu\\%[p]$" : "^popu(p)?$",
  "^pp\\%[op]$" : "^pp(op|o)?$",
  "^pre\\%[serve]$" : "^pre(serve|serv|ser|se|s)?$",
  "^prev\\%[ious]$" : "^prev(ious|iou|io|i)?$",
  "^pro\\%[mptfind]$" : "^pro(mptfind|mptfin|mptfi|mptf|mpt|mp|m)?$",
  "^prof\\%[ile]$" : "^prof(ile|il|i)?$",
  "^profd\\%[el]$" : "^profd(el|e)?$",
  "^promptr\\%[epl]$" : "^promptr(epl|ep|e)?$",
  "^ps\\%[earch]$" : "^ps(earch|earc|ear|ea|e)?$",
  "^ptN\\%[ext]$" : "^ptN(ext|ex|e)?$",
  "^pt\\%[ag]$" : "^pt(ag|a)?$",
  "^ptf\\%[irst]$" : "^ptf(irst|irs|ir|i)?$",
  "^ptj\\%[ump]$" : "^ptj(ump|um|u)?$",
  "^ptl\\%[ast]$" : "^ptl(ast|as|a)?$",
  "^ptn\\%[ext]$" : "^ptn(ext|ex|e)?$",
  "^ptp\\%[revious]$" : "^ptp(revious|reviou|revio|revi|rev|re|r)?$",
  "^ptr\\%[ewind]$" : "^ptr(ewind|ewin|ewi|ew|e)?$",
  "^pts\\%[elect]$" : "^pts(elect|elec|ele|el|e)?$",
  "^pu\\%[t]$" : "^pu(t)?$",
  "^pw\\%[d]$" : "^pw(d)?$",
  "^py3$" : "^py3$",
  "^py3f\\%[ile]$" : "^py3f(ile|il|i)?$",
  "^py\\%[thon]$" : "^py(thon|tho|th|t)?$",
  "^pyf\\%[ile]$" : "^pyf(ile|il|i)?$",
  "^python3$" : "^python3$",
  "^q\\%[uit]$" : "^q(uit|ui|u)?$",
  "^qa\\%[ll]$" : "^qa(ll|l)?$",
  "^quita\\%[ll]$" : "^quita(ll|l)?$",
  "^r\\%[ead]$" : "^r(ead|ea|e)?$",
  "^rec\\%[over]$" : "^rec(over|ove|ov|o)?$",
  "^red\\%[o]$" : "^red(o)?$",
  "^redi\\%[r]$" : "^redi(r)?$",
  "^redr\\%[aw]$" : "^redr(aw|a)?$",
  "^redraws\\%[tatus]$" : "^redraws(tatus|tatu|tat|ta|t)?$",
  "^reg\\%[isters]$" : "^reg(isters|ister|iste|ist|is|i)?$",
  "^res\\%[ize]$" : "^res(ize|iz|i)?$",
  "^ret\\%[ab]$" : "^ret(ab|a)?$",
  "^retu\\%[rn]$" : "^retu(rn|r)?$",
  "^rew\\%[ind]$" : "^rew(ind|in|i)?$",
  "^ri\\%[ght]$" : "^ri(ght|gh|g)?$",
  "^rightb\\%[elow]$" : "^rightb(elow|elo|el|e)?$",
  "^ru\\%[ntime]$" : "^ru(ntime|ntim|nti|nt|n)?$",
  "^rub\\%[y]$" : "^rub(y)?$",
  "^rubyd\\%[o]$" : "^rubyd(o)?$",
  "^rubyf\\%[ile]$" : "^rubyf(ile|il|i)?$",
  "^rund\\%[o]$" : "^rund(o)?$",
  "^rv\\%[iminfo]$" : "^rv(iminfo|iminf|imin|imi|im|i)?$",
  "^sN\\%[ext]$" : "^sN(ext|ex|e)?$",
  "^s\\%[ubstitute]$" : "^s(ubstitute|ubstitut|ubstitu|ubstit|ubsti|ubst|ubs|ub|u)?$",
  "^sa\\%[rgument]$" : "^sa(rgument|rgumen|rgume|rgum|rgu|rg|r)?$",
  "^sal\\%[l]$" : "^sal(l)?$",
  "^san\\%[dbox]$" : "^san(dbox|dbo|db|d)?$",
  "^sav\\%[eas]$" : "^sav(eas|ea|e)?$",
  "^sbN\\%[ext]$" : "^sbN(ext|ex|e)?$",
  "^sb\\%[uffer]$" : "^sb(uffer|uffe|uff|uf|u)?$",
  "^sba\\%[ll]$" : "^sba(ll|l)?$",
  "^sbf\\%[irst]$" : "^sbf(irst|irs|ir|i)?$",
  "^sbl\\%[ast]$" : "^sbl(ast|as|a)?$",
  "^sbm\\%[odified]$" : "^sbm(odified|odifie|odifi|odif|odi|od|o)?$",
  "^sbn\\%[ext]$" : "^sbn(ext|ex|e)?$",
  "^sbp\\%[revious]$" : "^sbp(revious|reviou|revio|revi|rev|re|r)?$",
  "^sbr\\%[ewind]$" : "^sbr(ewind|ewin|ewi|ew|e)?$",
  "^scrip\\%[tnames]$" : "^scrip(tnames|tname|tnam|tna|tn|t)?$",
  "^scripte\\%[ncoding]$" : "^scripte(ncoding|ncodin|ncodi|ncod|nco|nc|n)?$",
  "^scs\\%[cope]$" : "^scs(cope|cop|co|c)?$",
  "^se\\%[t]$" : "^se(t)?$",
  "^setf\\%[iletype]$" : "^setf(iletype|iletyp|ilety|ilet|ile|il|i)?$",
  "^setg\\%[lobal]$" : "^setg(lobal|loba|lob|lo|l)?$",
  "^setl\\%[ocal]$" : "^setl(ocal|oca|oc|o)?$",
  "^sf\\%[ind]$" : "^sf(ind|in|i)?$",
  "^sfir\\%[st]$" : "^sfir(st|s)?$",
  "^sh\\%[ell]$" : "^sh(ell|el|e)?$",
  "^sig\\%[n]$" : "^sig(n)?$",
  "^sil\\%[ent]$" : "^sil(ent|en|e)?$",
  "^sim\\%[alt]$" : "^sim(alt|al|a)?$",
  "^sl\\%[eep]$" : "^sl(eep|ee|e)?$",
  "^sla\\%[st]$" : "^sla(st|s)?$",
  "^sm\\%[agic]$" : "^sm(agic|agi|ag|a)?$",
  "^smap$" : "^smap$",
  "^smapc\\%[lear]$" : "^smapc(lear|lea|le|l)?$",
  "^sme\\%[nu]$" : "^sme(nu|n)?$",
  "^sn\\%[ext]$" : "^sn(ext|ex|e)?$",
  "^sni\\%[ff]$" : "^sni(ff|f)?$",
  "^sno\\%[magic]$" : "^sno(magic|magi|mag|ma|m)?$",
  "^snor\\%[emap]$" : "^snor(emap|ema|em|e)?$",
  "^snoreme\\%[nu]$" : "^snoreme(nu|n)?$",
  "^so\\%[urce]$" : "^so(urce|urc|ur|u)?$",
  "^sor\\%[t]$" : "^sor(t)?$",
  "^sp\\%[lit]$" : "^sp(lit|li|l)?$",
  "^spe\\%[llgood]$" : "^spe(llgood|llgoo|llgo|llg|ll|l)?$",
  "^spelld\\%[ump]$" : "^spelld(ump|um|u)?$",
  "^spelli\\%[nfo]$" : "^spelli(nfo|nf|n)?$",
  "^spellr\\%[epall]$" : "^spellr(epall|epal|epa|ep|e)?$",
  "^spellu\\%[ndo]$" : "^spellu(ndo|nd|n)?$",
  "^spellw\\%[rong]$" : "^spellw(rong|ron|ro|r)?$",
  "^spr\\%[evious]$" : "^spr(evious|eviou|evio|evi|ev|e)?$",
  "^sre\\%[wind]$" : "^sre(wind|win|wi|w)?$",
  "^st\\%[op]$" : "^st(op|o)?$",
  "^sta\\%[g]$" : "^sta(g)?$",
  "^star\\%[tinsert]$" : "^star(tinsert|tinser|tinse|tins|tin|ti|t)?$",
  "^startg\\%[replace]$" : "^startg(replace|replac|repla|repl|rep|re|r)?$",
  "^startr\\%[eplace]$" : "^startr(eplace|eplac|epla|epl|ep|e)?$",
  "^stj\\%[ump]$" : "^stj(ump|um|u)?$",
  "^stopi\\%[nsert]$" : "^stopi(nsert|nser|nse|ns|n)?$",
  "^sts\\%[elect]$" : "^sts(elect|elec|ele|el|e)?$",
  "^sun\\%[hide]$" : "^sun(hide|hid|hi|h)?$",
  "^sunm\\%[ap]$" : "^sunm(ap|a)?$",
  "^sunme\\%[nu]$" : "^sunme(nu|n)?$",
  "^sus\\%[pend]$" : "^sus(pend|pen|pe|p)?$",
  "^sv\\%[iew]$" : "^sv(iew|ie|i)?$",
  "^sw\\%[apname]$" : "^sw(apname|apnam|apna|apn|ap|a)?$",
  "^sy\\%[ntax]$" : "^sy(ntax|nta|nt|n)?$",
  "^sync\\%[bind]$" : "^sync(bind|bin|bi|b)?$",
  "^t$" : "^t$",
  "^tN\\%[ext]$" : "^tN(ext|ex|e)?$",
  "^ta\\%[g]$" : "^ta(g)?$",
  "^tab$" : "^tab$",
  "^tabN\\%[ext]$" : "^tabN(ext|ex|e)?$",
  "^tabc\\%[lose]$" : "^tabc(lose|los|lo|l)?$",
  "^tabdo$" : "^tabdo$",
  "^tabe\\%[dit]$" : "^tabe(dit|di|d)?$",
  "^tabf\\%[ind]$" : "^tabf(ind|in|i)?$",
  "^tabfir\\%[st]$" : "^tabfir(st|s)?$",
  "^tabl\\%[ast]$" : "^tabl(ast|as|a)?$",
  "^tabm\\%[ove]$" : "^tabm(ove|ov|o)?$",
  "^tabn\\%[ext]$" : "^tabn(ext|ex|e)?$",
  "^tabnew$" : "^tabnew$",
  "^tabo\\%[nly]$" : "^tabo(nly|nl|n)?$",
  "^tabp\\%[revious]$" : "^tabp(revious|reviou|revio|revi|rev|re|r)?$",
  "^tabr\\%[ewind]$" : "^tabr(ewind|ewin|ewi|ew|e)?$",
  "^tabs$" : "^tabs$",
  "^tags$" : "^tags$",
  "^tc\\%[l]$" : "^tc(l)?$",
  "^tcld\\%[o]$" : "^tcld(o)?$",
  "^tclf\\%[ile]$" : "^tclf(ile|il|i)?$",
  "^te\\%[aroff]$" : "^te(aroff|arof|aro|ar|a)?$",
  "^tf\\%[irst]$" : "^tf(irst|irs|ir|i)?$",
  "^th\\%[row]$" : "^th(row|ro|r)?$",
  "^tj\\%[ump]$" : "^tj(ump|um|u)?$",
  "^tl\\%[ast]$" : "^tl(ast|as|a)?$",
  "^tm\\%[enu]$" : "^tm(enu|en|e)?$",
  "^tn\\%[ext]$" : "^tn(ext|ex|e)?$",
  "^to\\%[pleft]$" : "^to(pleft|plef|ple|pl|p)?$",
  "^tp\\%[revious]$" : "^tp(revious|reviou|revio|revi|rev|re|r)?$",
  "^tr\\%[ewind]$" : "^tr(ewind|ewin|ewi|ew|e)?$",
  "^try$" : "^try$",
  "^ts\\%[elect]$" : "^ts(elect|elec|ele|el|e)?$",
  "^tu\\%[nmenu]$" : "^tu(nmenu|nmen|nme|nm|n)?$",
  "^u\\%[ndo]$" : "^u(ndo|nd|n)?$",
  "^una\\%[bbreviate]$" : "^una(bbreviate|bbreviat|bbrevia|bbrevi|bbrev|bbre|bbr|bb|b)?$",
  "^undoj\\%[oin]$" : "^undoj(oin|oi|o)?$",
  "^undol\\%[ist]$" : "^undol(ist|is|i)?$",
  "^unh\\%[ide]$" : "^unh(ide|id|i)?$",
  "^unl\\%[et]$" : "^unl(et|e)?$",
  "^unlo\\%[ckvar]$" : "^unlo(ckvar|ckva|ckv|ck|c)?$",
  "^unm\\%[ap]$" : "^unm(ap|a)?$",
  "^unme\\%[nu]$" : "^unme(nu|n)?$",
  "^uns\\%[ilent]$" : "^uns(ilent|ilen|ile|il|i)?$",
  "^up\\%[date]$" : "^up(date|dat|da|d)?$",
  "^v\\%[global]$" : "^v(global|globa|glob|glo|gl|g)?$",
  "^ve\\%[rsion]$" : "^ve(rsion|rsio|rsi|rs|r)?$",
  "^verb\\%[ose]$" : "^verb(ose|os|o)?$",
  "^vert\\%[ical]$" : "^vert(ical|ica|ic|i)?$",
  "^vi\\%[sual]$" : "^vi(sual|sua|su|s)?$",
  "^vie\\%[w]$" : "^vie(w)?$",
  "^vim\\%[grep]$" : "^vim(grep|gre|gr|g)?$",
  "^vimgrepa\\%[dd]$" : "^vimgrepa(dd|d)?$",
  "^viu\\%[sage]$" : "^viu(sage|sag|sa|s)?$",
  "^vm\\%[ap]$" : "^vm(ap|a)?$",
  "^vmapc\\%[lear]$" : "^vmapc(lear|lea|le|l)?$",
  "^vme\\%[nu]$" : "^vme(nu|n)?$",
  "^vn\\%[oremap]$" : "^vn(oremap|orema|orem|ore|or|o)?$",
  "^vne\\%[w]$" : "^vne(w)?$",
  "^vnoreme\\%[nu]$" : "^vnoreme(nu|n)?$",
  "^vs\\%[plit]$" : "^vs(plit|pli|pl|p)?$",
  "^vu\\%[nmap]$" : "^vu(nmap|nma|nm|n)?$",
  "^vunme\\%[nu]$" : "^vunme(nu|n)?$",
  "^wN\\%[ext]$" : "^wN(ext|ex|e)?$",
  "^w\\%[rite]$" : "^w(rite|rit|ri|r)?$",
  "^wa\\%[ll]$" : "^wa(ll|l)?$",
  "^wh\\%[ile]$" : "^wh(ile|il|i)?$",
  "^wi\\%[nsize]$" : "^wi(nsize|nsiz|nsi|ns|n)?$",
  "^winc\\%[md]$" : "^winc(md|m)?$",
  "^windo$" : "^windo$",
  "^winp\\%[os]$" : "^winp(os|o)?$",
  "^wn\\%[ext]$" : "^wn(ext|ex|e)?$",
  "^wp\\%[revious]$" : "^wp(revious|reviou|revio|revi|rev|re|r)?$",
  "^wq$" : "^wq$",
  "^wqa\\%[ll]$" : "^wqa(ll|l)?$",
  "^ws\\%[verb]$" : "^ws(verb|ver|ve|v)?$",
  "^wu\\%[ndo]$" : "^wu(ndo|nd|n)?$",
  "^wv\\%[iminfo]$" : "^wv(iminfo|iminf|imin|imi|im|i)?$",
  "^x\\%[it]$" : "^x(it|i)?$",
  "^xa\\%[ll]$" : "^xa(ll|l)?$",
  "^xm\\%[ap]$" : "^xm(ap|a)?$",
  "^xmapc\\%[lear]$" : "^xmapc(lear|lea|le|l)?$",
  "^xme\\%[nu]$" : "^xme(nu|n)?$",
  "^xn\\%[oremap]$" : "^xn(oremap|orema|orem|ore|or|o)?$",
  "^xnoreme\\%[nu]$" : "^xnoreme(nu|n)?$",
  "^xu\\%[nmap]$" : "^xu(nmap|nma|nm|n)?$",
  "^xunme\\%[nu]$" : "^xunme(nu|n)?$",
  "^y\\%[ank]$" : "^y(ank|an|a)?$",
  "^z$" : "^z$",
  "^{" : "^{",
  "^|" : "^\\|",
  "^||" : "^\\|\\|",
  "^}" : "^}",
  "[Ee][-+]\\d" : "[Ee][-+]\\d",
  "^\\s*\\\\" : "^\\s*\\\\",
}

def viml_add(lst, item):
    lst.append(item)

def viml_call(func, *args):
    func(*args)

def viml_empty(obj):
    return len(obj) == 0

def viml_eqreg(s, reg):
    return re.search(pat_vim2py[reg], s, re.IGNORECASE)

def viml_eqregh(s, reg):
    return re.search(pat_vim2py[reg], s)

def viml_eqregq(s, reg):
    return re.search(pat_vim2py[reg], s, re.IGNORECASE)

def viml_escape(s, chars):
    r = ''
    for c in s:
        if c in chars:
            r += "\\" + c
        else:
            r += c
    return r

def viml_extend(obj, item):
    obj.extend(item)

def viml_insert(lst, item, idx = 0):
    lst.insert(idx, item)

def viml_join(lst, sep):
    return sep.join(lst)

def viml_keys(obj):
    return obj.keys()

def viml_len(obj):
    return len(obj)

def viml_printf(*args):
    if len(args) == 1:
        return args[0]
    else:
        return args[0] % args[1:]

def viml_range(start, end=None):
    if end is None:
        return range(start)
    else:
        return range(start, end + 1)

def viml_readfile(path):
    lines = []
    f = open(path)
    for line in f.readlines():
        lines.append(line.rstrip("\r\n"))
    f.close()
    return lines

def viml_remove(lst, idx):
    del lst[idx]

def viml_split(s, sep):
    if sep == "\\zs":
        return s
    raise Exception("NotImplemented")

def viml_str2nr(s, base=10):
    return int(s, base)

def viml_string(obj):
    return str(obj)

def viml_has_key(obj, key):
    return key in obj

